[package]
name = "create-and-use-variables"
version = "0.1.0"
authors = ["Henrico Lazuroz <henrico.almeida@fcamara.com.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
